---
- name: Update and upgrade Ubuntu/Debian servers
  hosts: all
  become: true  # Run as sudo/root

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Upgrade all packages
      apt:
        upgrade: dist
      when: ansible_distribution == "Ubuntu"
