---
- name: Update and upgrade Debian server
  hosts: all
  become: yes  # Run as sudo/root
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
      retries: 5
      delay: 10
      until: result is succeeded

    - name: Upgrade all packages
      apt:
        upgrade: dist
      retries: 5
      delay: 10
      until: result is succeeded
