---
- name: Update and upgrade Debian server
  hosts: all
  become: true  # Run as sudo/root

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
