---
- name: Update and upgrade Ubuntu/Debian servers
  hosts: all
  become: true  # Run as sudo/root
  become_method: sudo

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Upgrade all packages
      apt:
        upgrade: dist
      when: ansible_distribution in ["Debian", "Ubuntu"]
