---
- name: Update and upgrade Debian server
  hosts: all
  become: true  # Run as sudo/root

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        lock_timeout: 180  # Increase timeout for lock handling

    - name: Upgrade all packages
      apt:
        upgrade: dist
        lock_timeout: 180  # Increase timeout for lock handling
