---
- name: Update and upgrade Debian server
  hosts: all
  become: yes  # Run as sudo/root
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Reboot if required
      reboot:
        msg: "Rebooting after upgrade if needed"
        reboot_timeout: 600
      when: ansible_facts['reboot_required'] | default(false)
