---
- name: Install and configure Fail2Ban
  hosts: all
  become: true # Run as sudo/root

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Ensure Fail2Ban is running and enabled
      service:
        name: fail2ban
        state: started
        enabled: true

    - name: Create a local copy of the jail.local file
      copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        remote_src: yes
        owner: root
        group: root
        mode: "0644"
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Restart Fail2Ban to apply configuration
      service:
        name: fail2ban
        state: restarted
