---
- name: Set up a new user and add to the sudo group
  hosts: all
  become: true

  tasks:
    - name: Install sudo if not installed
      apt:
        name: sudo
        state: present

    - name: Create a new user
      user:
        name: "{{ lookup('env', 'user') }}"
        password: "{{ lookup('env', 'password') | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        createhome: yes

    - name: Add the user to the sudo group
      user:
        name: "{{ lookup('env', 'user') }}"
        groups: sudo
        append: yes

    # - name: Allow passwordless sudo for the new user
    #   lineinfile:
    #     path: /etc/sudoers
    #     regexp: "^{{ lookup('env', 'user') }} ALL=(ALL) NOPASSWD:ALL"
    #     line: "{{ lookup('env', 'user') }} ALL=(ALL) NOPASSWD:ALL"
    #     state: present
    #     validate: "visudo -cf %s"

    - name: Ensure sudo group can use sudo without password
      lineinfile:
        path: /etc/sudoers
        regexp: "^%sudo   ALL=(ALL:ALL) ALL"
        line: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"
        state: present
        validate: "visudo -cf %s"
